import type { LineItem, Offer, WeeklyTask } from "./types";

export const STARTING_CAPITAL = 100_000;

export const DEFAULT_ITEMS: LineItem[] = [
  {
    id: "rent",
    category: "living",
    name: "宜蘭／羅東套房租金",
    amount: 9000,
    enabled: true,
    cadence: "monthly",
    note: "市區一房常見落在 8,000–12,000。礁溪觀光區偏高，員山、壯圍可再壓。",
  },
  {
    id: "utilities",
    category: "living",
    name: "水電瓦斯與家用網路",
    amount: 2500,
    enabled: true,
    cadence: "monthly",
    note: "遠距工作把家當辦公室，光纖比咖啡廳穩定。",
  },
  {
    id: "food",
    category: "living",
    name: "伙食",
    amount: 9000,
    enabled: true,
    cadence: "monthly",
    note: "自己煮加在地小吃。台北外食水準在宜蘭通常能再省 2–4 成。",
  },
  {
    id: "transport",
    category: "living",
    name: "機車油資與保險",
    amount: 1500,
    enabled: true,
    cadence: "monthly",
    note: "接案以遠距為主，實體拜訪才騎車。",
  },
  {
    id: "nhi",
    category: "living",
    name: "健保（第六類）",
    amount: 1000,
    enabled: true,
    cadence: "monthly",
    note: "無雇主時以第六類投保。實際金額依年度費率與依附眷屬而變。",
  },
  {
    id: "labor",
    category: "living",
    name: "職業工會勞保（選擇性）",
    amount: 1800,
    enabled: true,
    cadence: "monthly",
    note: "自營者可透過職業工會加保。現金極緊時可暫緩，但不建議長期裸奔。",
  },
  {
    id: "misc",
    category: "living",
    name: "日用雜支",
    amount: 1500,
    enabled: true,
    cadence: "monthly",
    note: "洗衣、日用品、臨時交通。",
  },
  {
    id: "cursor",
    category: "tooling",
    name: "Cursor 或同等 Agent 編輯器",
    amount: 700,
    enabled: true,
    cadence: "monthly",
    note: "這是核心生產工具。十萬預算裡，這筆比辦公室更值得。",
  },
  {
    id: "phone",
    category: "tooling",
    name: "手機門號",
    amount: 599,
    enabled: true,
    cadence: "monthly",
    note: "客戶聯繫與收驗證。不必上最貴方案。",
  },
  {
    id: "cowork",
    category: "tooling",
    name: "共創／共享座位（選擇性）",
    amount: 3000,
    enabled: false,
    cadence: "monthly",
    note: "預設在家。需要社交或視訊背景時再開。宜蘭、羅東偶有彈性座位。",
  },
  {
    id: "domain",
    category: "cloud",
    name: "網域（年繳攤提）",
    amount: 40,
    enabled: true,
    cadence: "monthly",
    note: "年費約 400–600，這裡按月攤。Cloudflare Registrar 通常較省。",
  },
  {
    id: "pages",
    category: "cloud",
    name: "網站與 Worker 託管",
    amount: 0,
    enabled: true,
    cadence: "monthly",
    note: "Cloudflare Pages / Workers 免費額度夠一人工作室示範與前幾個客戶。",
  },
  {
    id: "llm",
    category: "cloud",
    name: "LLM API 用量",
    amount: 2500,
    enabled: true,
    cadence: "monthly",
    note: "沒案件時可降到 0，用本系統內建 Agent。接到案再按用量開。",
  },
  {
    id: "email",
    category: "cloud",
    name: "商務信箱轉寄",
    amount: 0,
    enabled: true,
    cadence: "monthly",
    note: "Cloudflare Email Routing 免費把 hello@你的網域 轉到現有信箱。",
  },
  {
    id: "laptop",
    category: "setup",
    name: "二手筆電補強（一次）",
    amount: 0,
    enabled: false,
    cadence: "once",
    note: "已有能跑瀏覽器與編輯器的筆電就維持 0。若要買，宜蘭二手市場約 12,000–22,000。",
  },
  {
    id: "legal",
    category: "setup",
    name: "行號設立與印章（一次）",
    amount: 2500,
    enabled: true,
    cadence: "once",
    note: "十萬資本先走獨資行號，不急著開有限公司。此為規費與雜支估列，非正式報價。",
  },
  {
    id: "brand",
    category: "setup",
    name: "網域首年與設計基本盤（一次）",
    amount: 800,
    enabled: true,
    cadence: "once",
    note: "網域 + 簡單識別。不要把預算花在華麗官網外包。",
  },
];

export const OFFERS: Offer[] = [
  {
    id: "spark",
    name: "火花診斷",
    tag: "7 天",
    price: 18000,
    deliveryDays: 7,
    hours: 16,
    apiCost: 400,
    summary: "幫一間在地或遠距小公司找出最值得交給 Agent 的一件工作，並交一份可執行的藍圖。",
    deliverables: [
      "現況訪談與流程圖",
      "一個 Agent 使用情境與提示詞",
      "雲端架構草圖（免費額度優先）",
      "30 天導入清單",
    ],
    bestFor: "還在觀望的店家、工作室、診所後台。用來快速進帳、建立信任。",
  },
  {
    id: "build",
    name: "可交件 Agent",
    tag: "21 天",
    price: 48000,
    deliveryDays: 21,
    hours: 48,
    apiCost: 1800,
    summary: "把一個重複流程做成可上線的 Agent：客服草稿、報價、預約、或內部知識問答。",
    deliverables: [
      "可示範的 Agent 介面",
      "Cloudflare／GitHub 部署",
      "操作手冊與提示詞庫",
      "兩週內的修正額度",
    ],
    bestFor: "已有明確痛點、願意在一個流程上付費的客戶。這是回本主力。",
  },
  {
    id: "retain",
    name: "月費守夜",
    tag: "每月",
    price: 12000,
    deliveryDays: 30,
    hours: 12,
    apiCost: 900,
    summary: "Agent 上線後的遠距維運：用量監控、提示詞迭代、小需求、每月一次流程回顧。",
    deliverables: [
      "用量與異常摘要",
      "一次流程改善",
      "工作日 24 小時內回應",
      "月報（給老闆看的一頁）",
    ],
    bestFor: "做完建置案後轉成穩定現金流，降低下個月是否有案的焦慮。",
  },
];

export const WEEKLY_RITUAL: WeeklyTask[] = [
  {
    id: "mon",
    weekday: "一",
    title: "管道與名單",
    detail: "寫 5 封開發信或既有人脈訊息。不寫部落格長文，只約 20 分鐘通話。",
  },
  {
    id: "tue",
    weekday: "二",
    title: "做示範",
    detail: "把作品集 Agent 再磨一個真實場景。宜蘭在地案例優先：民宿、診所、餐飲、農產。",
  },
  {
    id: "wed",
    weekday: "三",
    title: "深工",
    detail: "若有案件就交付；沒有就做下一個可展示模組。上午深度工作，下午回訊。",
  },
  {
    id: "thu",
    weekday: "四",
    title: "報價與跟進",
    detail: "所有詢問在當天出草報。超過三天沒回的名單再跟一次。",
  },
  {
    id: "fri",
    weekday: "五",
    title: "帳與雲",
    detail: "看 API 帳單、跑道餘額、下週要交付的三件事。沒有第三件事就去開發。",
  },
  {
    id: "sat",
    weekday: "六",
    title: "在地半天",
    detail: "市場、店家、或一個實體拜訪。遠距不是與宜蘭斷開，是把生活成本留在這裡。",
  },
  {
    id: "sun",
    weekday: "日",
    title: "停機",
    detail: "不接新需求。下雨天正好休息，週一才有力氣把 Agent 交出去。",
  },
];

export const PLAYBOOK = [
  {
    window: "第 1–7 天",
    title: "把廠房搭起來",
    items: [
      "決定接案身份：先個人或獨資行號，不急有限公司",
      "買網域、開 GitHub、部署本系統當作品集",
      "定三個套餐價格，不再臨時開價",
      "列出 30 個可說話的人：前同事、親戚店家、社團",
    ],
  },
  {
    window: "第 8–21 天",
    title: "做出兩個能點的東西",
    items: [
      "示範 A：店家客服／訂位草稿 Agent",
      "示範 B：報價與週報 Agent（就是本系統的精神）",
      "每週至少 10 次對話，目標約到 3 次診斷",
      "API 還沒有收入前維持 0 用量",
    ],
  },
  {
    window: "第 22–45 天",
    title: "開出第一張帳單",
    items: [
      "主力賣火花診斷 18,000，降低客戶決策門檻",
      "診斷結束一定附建置報價，不要只送報告",
      "收款 50% 開工、50% 上線",
      "交付時邀月費守夜，哪怕打九折也要試著留下",
    ],
  },
  {
    window: "第 46–90 天",
    title: "讓跑道轉正",
    items: [
      "一個建置案加月費能止血，但打平通常要兩到三份月費，或診斷／建置持續進來",
      "拒絕客製到虧工時的案子，工時寫在報價上",
      "把第二個產業模組化，不要每個客戶從零",
      "現金水位低於兩個月生活費時，只做開發與交付，不做新功能幻想",
    ],
  },
];

export const STACK = [
  {
    layer: "門面",
    choice: "Cloudflare Pages + 自有網域",
    monthly: 0,
    why: "全球 CDN、HTTPS、中文站夠用。十萬預算不該付主機月費。",
  },
  {
    layer: "Agent 執行",
    choice: "先用本系統規則引擎，有案再接 OpenAI 相容 API",
    monthly: 0,
    why: "沒有客戶時，付 token 是在燒生活費。",
  },
  {
    layer: "原始碼",
    choice: "GitHub 私有或公開 repo",
    monthly: 0,
    why: "遠距協作與版本就是雲端廠房。",
  },
  {
    layer: "信箱",
    choice: "Email Routing → 既有 Gmail",
    monthly: 0,
    why: "看起來像公司，成本是 0。",
  },
  {
    layer: "生產力",
    choice: "Cursor + 本系統工作室後台",
    monthly: 700,
    why: "一人公司的員工就是 Agent。編輯器是薪水簿上最該留的人。",
  },
];
